// src/app/privacy-policy/page.tsx

import Breadcrumb from "@/components/Common/Breadcrumb";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Melofy",
  description: "Learn about how Melofy collects, uses, and protects your personal information.",
  // other metadata
};

const PrivacyPolicyPage = () => {
  const lastUpdated = "June 6, 2025"; // <<< UPDATE THIS TO THE CURRENT DATE WHEN FINALIZED
  const appName = "Melofy";
  const operatorName = "Nyan Lin Htut"; // Your Name

  return (
    <>
      <Breadcrumb
        pageName="Privacy Policy"
        description={`Last Updated: ${lastUpdated}`}
      />

      <section className="pb-16 md:pb-20 lg:pb-24 pt-10">
        <div className="container">
          <div className="wow fadeInUp rounded-md bg-primary/[3%] px-8 py-10 dark:bg-dark sm:p-10 lg:px-8 xl:p-10">
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              {operatorName} ("us", "we", or "our") operates the {appName} web application (hereinafter referred to as the "Service").
              This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
            </p>

            <h3 className="mb-4 text-xl font-semibold text-black dark:text-white">1. Information Collection and Use</h3>
            <p className="mb-4 text-base text-body-color dark:text-body-color-dark">
              We collect different types of information for various purposes to provide and improve our Service to you.
            </p>
            <h4 className="mb-2 text-lg font-medium text-black dark:text-white">Types of Data Collected</h4>
            <p className="mb-2 text-base font-semibold text-body-color dark:text-body-color-dark">Personal Data (If User Accounts are Implemented)</p>
            <p className="mb-4 text-base text-body-color dark:text-body-color-dark">
              While using certain features of our Service that require authentication (e.g., saving playlists, user profiles, if implemented), we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). This may include, but is not limited to:
              <ul className="list-disc pl-6 mt-2">
                <li>Email address</li>
                <li>Username or unique identifier</li>
                {/* Add other PII if collected, e.g., via Cognito attributes or a future profile system */}
              </ul>
            </p>
            <p className="mb-2 text-base font-semibold text-body-color dark:text-body-color-dark">Usage Data (Prompts & Interactions)</p>
            <p className="mb-4 text-base text-body-color dark:text-body-color-dark">
              We collect the textual inputs (prompts, moods, vibes, duration, taste preferences, sample songs - collectively "Usage Prompts") you provide to the Service for the purpose of generating playlists. This data is transmitted to the OpenAI API for processing. We may temporarily log these prompts for debugging and service improvement purposes, but do not associate them with identifiable Personal Data unless necessary for account-specific features (like playlist history, if implemented).
            </p>
            <p className="mb-2 text-base font-semibold text-body-color dark:text-body-color-dark">Spotify Data</p>
            <p className="mb-4 text-base text-body-color dark:text-body-color-dark">
              To create playlists in your Spotify account, the Service requires authorization to access your Spotify account via OAuth 2.0. We may access:
              <ul className="list-disc pl-6 mt-2">
                <li>Your Spotify user ID (for identifying you to Spotify).</li>
                <li>Permission to create and modify public and private playlists.</li>
                <li>Permission to add tracks to playlists.</li>
              </ul>
              We do not store your Spotify password. We may store Spotify playlist IDs and URLs generated by {appName} if a feature to save playlist history is implemented.
            </p>
            <p className="mb-2 text-base font-semibold text-body-color dark:text-body-color-dark">Cookies & Tracking Data</p>
            <p className="mb-4 text-base text-body-color dark:text-body-color-dark">
              We may use cookies and similar tracking technologies to track activity on our Service and hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service. (Specify if you use analytics or other specific cookie-based services).
            </p>


            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">2. Use of Data</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              {operatorName} uses the collected data for purposes such as:
              <ul className="list-disc space-y-1 pl-6 mt-2">
                <li>To provide, operate, and maintain our Service.</li>
                <li>To enable playlist generation based on your Usage Prompts via the OpenAI API.</li>
                <li>To interact with the Spotify API to create playlists in your Spotify account.</li>
                <li>To manage user accounts and authentication (if implemented).</li>
                <li>To notify you about changes to our Service.</li>
                <li>To provide customer support.</li>
                <li>To monitor the usage of our Service (e.g., for identifying popular features or potential issues).</li>
                <li>To detect, prevent and address technical issues.</li>
              </ul>
            </p>

            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">3. Service Providers & Data Transfers</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services, or assist us in analyzing how our Service is used. These third parties have access to your Personal Data or Usage Prompts only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
              <ul className="list-disc space-y-1 pl-6 mt-2">
                <li><strong>OpenAI, L.L.C.:</strong> For processing Usage Prompts to generate song suggestions. Their Privacy Policy can be found at <a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">https://openai.com/policies/privacy-policy</a>.</li>
                <li><strong>Spotify AB:</strong> For accessing your Spotify account to create playlists. Their Privacy Policy can be found at <a href="https://www.spotify.com/legal/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">https://www.spotify.com/legal/privacy-policy/</a>.</li>
                <li><strong>Amazon Web Services (AWS):</strong> Our backend infrastructure, including API Gateway, Lambda functions, and potentially DynamoDB (for future features like saved playlists) and Cognito (for user authentication, if implemented), is hosted on AWS.</li>
                <li><strong>Vercel Inc.:</strong> Our frontend application is hosted on Vercel. Their Privacy Policy can be found at <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">https://vercel.com/legal/privacy-policy</a>.</li>
              </ul>
              Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of Singapore where the data protection laws may differ. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
            </p>

            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">4. Data Security</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              The security of your data is important to us. We strive to use commercially acceptable means to protect your Personal Data, such as HTTPS for data in transit. However, no method of transmission over the Internet or method of electronic storage is 100% secure. While we aim to protect your Personal Data, we cannot guarantee its absolute security.
            </p>
            
            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">5. Data Retention</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
                We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, or as required by law. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies. Usage Prompts sent to OpenAI may be subject to OpenAI's data retention policies.
            </p>

            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">6. Your Data Protection Rights Under Singapore's Personal Data Protection Act (PDPA)</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              If you are a resident of Singapore, you have certain data protection rights. {operatorName} aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
              If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us. In certain circumstances, you have the following data protection rights:
              <ul className="list-disc space-y-1 pl-6 mt-2">
                <li>The right to access, update or delete the information we have on you.</li>
                <li>The right of rectification.</li>
                <li>The right to object.</li>
                <li>The right of restriction.</li>
                <li>The right to data portability (where applicable).</li>
                <li>The right to withdraw consent.</li>
              </ul>
              Please note that we may ask you to verify your identity before responding to such requests.
            </p>
            
            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">7. Children's Privacy</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              Our Service does not knowingly address anyone under the age of 13 ("Children"). We do not knowingly collect personally identifiable information from children under 13. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
            </p>

            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">8. Changes to This Privacy Policy</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>

            <h3 className="mb-4 mt-6 text-xl font-semibold text-black dark:text-white">9. Contact Us</h3>
            <p className="mb-6 text-base text-body-color dark:text-body-color-dark">
              If you have any questions about this Privacy Policy, please contact us: [Your Contact Email or Link to Contact Page]
            </p>
          </div>
        </div>
      </section>
    </>
  );
};

export default PrivacyPolicyPage;